name: Sandbox
on: 
#  repository_dispatch:
  workflow_dispatch:
#    inputs:
#      repo-name: 
#        description: 'Name of the repository to be created'
#        required: true
#        default: ''

jobs:
  create-repository:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
